### ISSUE TITLE
Sponsors Listing

### ISSUE THREAD

**Issue by jonasfuchs** [pioniergarage/launchpad#2]
Problem #1: There aren't any sponsors listed on the website yet.
Problem #2: We need the sponsors approval for the listing.

Solution 
Step #1: Temporarily insert Logo of Daimler & EnBW (different sizes)
Step #2: Send Screenshot to Andreas F. and wait for approval
Step #3: Apply changes to live Website!

**Comment by jonasfuchs** [comment]
Correction to Step #1: We dont need confirmation of EnBW - so just do it for the Daimler Logo

**Comment by lorey** [comment]
Done. Waiting for Andreas to give his approval.

**Comment by andreas-fischer** [comment]
Got approval from EnBW, but Daimler demands a change in line with their design guidelines. Excerpt from the feedback mail:

"Kann leider nicht so bleiben. Bei Kooperationen muss das Logo schwarz sein. Auch die Abstände sind genau definiert.
Unter folgendem Link, findest Du das schwarze Logo als Download und unter dem Reiter Design Manuals sind die nötigen Abstände nochmal genau beschrieben:

https://designnavigator.daimler.com/daimler_downloads?lang=en"

As soon as the alternative logo is in place I can ask for approval again.

**Comment by lorey** [comment]
For reference:
- Changing to the b/w version
- Cropping to match https://designnavigator.daimler.com/files/images/__cache/content/Daimler/basic_elements/Unternehmenszeichen_Abb_06.png.jpg

**Comment by andreas-fischer** [comment]
New logo layout is approved by Daimler. New iteration of the website can go live and issue can be closed.

**Comment by lorey** [comment]
Thanks. The new version is now available at http://launchpad.pioniergarage.de
