### ISSUE TITLE
Duplicate ids

### ISSUE THREAD

**Issue by lorey** [pioniergarage/launchpad#3]
The HTML id value "intro" is used twice but must be used only once. As this is a minor change, one of you guys could try his luck. Steps:
- Have git installed
- Clone repo `git clone https://github.com/pioniergarage/launchpad.git`
- Change ID in the index.html file
- Check that the layout of the website still works, if not, ask for help ;)
- add the file to git (`git add index.html`)
- commit with a commit message containing the issue, for example (`git commit -m "Changed duplicate ID. Closes #3"`)
- upload by doing a `git push origin master`

**Comment by andreas-fischer** [comment]
I got the fix in a branch, but apparently lack upload rights. More information in Slack.

**Comment by lorey** [comment]
My fault. You weren't in the launchpad team which gives you write access. Could you try again?
